AllCops:
  Exclude:
    - './swagger-ui/'
    - 'config.ru'
    - './lib/tasks/*.rake'
    - './app/geocalc/distance.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
