AllCops:
  Exclude:
    - 'public/frontend/config.ru'
    - 'config.ru'
    - './lib/tasks/*.rake'
    - './app/geocalc/distance.rb'
    - './app/geocalc/bearing.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
