version: '3'

services:
  api:
    build: .
    image: d2d/api
    container_name: d2d-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: curl --fail -s http://localhost:3000/api/v1/vehicles/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
