FROM node:12.2.0-alpine

ENV APP_HOME /app

WORKDIR $APP_HOME
ENV PATH /app/node_modules/.bin:$PATH

ADD . $APP_HOME
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

CMD ["yarn", "start-prod"]
