version: '3'

services:
  redis:
    image: redis:5.0-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data
    restart: always

  api:
    build: .
    image: d2d/api
    container_name: d2d-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: curl --fail -s http://localhost:3000/api/v1/vehicles/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis
